import fitz  # PyMuPDF
import sys

# --- 共通設定 (A4 / 72dpi) ---
PAGE_WIDTH = 595.276  # A4 width (pt)
PAGE_HEIGHT = 841.89  # A4 height (pt)
MM = 72 / 25.4  # mm to pt conversion

# Erstellerの線と同じ位置設定
LINE_MARGIN_X = 20 * MM
HEADER_LINE_Y = PAGE_HEIGHT - (14.8 * MM)
FOOTER_LINE_Y = 17 * MM
LINE_COLOR = (0.7, 0.7, 0.7)  # 薄いグレー

# フォント設定 (環境に合わせて変更可)
FONT_PATH = r"C:\Windows\Fonts\msgothic.ttc"
FONT_NAME = "msgothic"

# Index Key 選択肢
OPTIONS = [
    "タスク",
    "アイデア",
    "思考・考察",
    "コミュニケーション",
    "学習・情報収集",
    "日常・その他",
]


def draw_guides(page):
    """ヘッダー・フッターのガイド線を描画"""
    # Header Line
    page.draw_line(
        fitz.Point(LINE_MARGIN_X, HEADER_LINE_Y),
        fitz.Point(PAGE_WIDTH - LINE_MARGIN_X, HEADER_LINE_Y),
        color=LINE_COLOR,
        width=0.5,
    )
    # Footer Line
    page.draw_line(
        fitz.Point(LINE_MARGIN_X, FOOTER_LINE_Y),
        fitz.Point(PAGE_WIDTH - LINE_MARGIN_X, FOOTER_LINE_Y),
        color=LINE_COLOR,
        width=0.5,
    )


def generate_form_a4():
    """フォーム付き A4 テンプレート (1ページ目用)"""
    filename = "Synapsen_BlankSheet_A4_Form.pdf"
    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)

    # メタデータ (正規化スキップ)
    doc.set_metadata(
        {
            "keywords": "Synapsen:SkipNormalization",
            "producer": f"Generated by Python {sys.version.split()[0]} with PyMuPDF",
            "title": "Synapsen A4 Form Template",
        }
    )

    draw_guides(page)

    # --- フォーム追加 ---
    try:
        page.insert_font(fontfile=FONT_PATH, fontname=FONT_NAME)
    except Exception:
        pass  # デフォルトフォント使用

    # 設定値 (DotLegalPad_Config 相当)
    raw_form_width = 375
    raw_form_height = 60

    # スケーリング (200dpi -> 72dpi)
    scale_factor = 72 / 200
    form_width = raw_form_width * scale_factor
    form_height = raw_form_height * scale_factor

    # 配置 (左マージン揃え, 上マージンの30%の位置)
    CM = 72 / 2.54
    x0 = 1 * CM
    y0 = 2.2 * CM * 0.3
    x1 = x0 + form_width
    y1 = y0 + form_height

    widget = fitz.Widget()
    widget.rect = fitz.Rect(x0, y0, x1, y1)

    widget.field_type = fitz.PDF_WIDGET_TYPE_COMBOBOX
    widget.field_flags = fitz.PDF_CH_FIELD_IS_COMBO
    widget.field_name = "category_choice"
    widget.choice_values = OPTIONS
    widget.text_font = FONT_NAME
    widget.text_fontsize = 12
    widget.field_value = ""

    page.add_widget(widget)

    doc.save(filename)
    doc.close()
    print(f"作成完了: {filename}")


def generate_note_a4():
    """フォーム無し A4 テンプレート (2ページ目以降用)"""
    filename = "Synapsen_BlankSheet_A4.pdf"
    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)

    # メタデータ (ページ追加可能 + 正規化スキップ)
    doc.set_metadata(
        {
            "keywords": "DPDocType:notebook; Synapsen:SkipNormalization",
            "producer": f"Generated by Python {sys.version.split()[0]} with PyMuPDF",
            "title": "Synapsen A4 Note Template",
        }
    )

    draw_guides(page)

    doc.save(filename)
    doc.close()
    print(f"作成完了: {filename}")


if __name__ == "__main__":
    generate_form_a4()
    generate_note_a4()
