import fitz
import sys

# --- 共通設定 (A5 / 72dpi) ---
PAGE_WIDTH = 419.528  # A5 width (pt)
PAGE_HEIGHT = 595.276  # A5 height (pt)
MM = 72 / 25.4

# Erstellerの線と同じ位置設定
LINE_MARGIN_X = 20 * MM
HEADER_LINE_Y = PAGE_HEIGHT - (14.8 * MM)
FOOTER_LINE_Y = 17 * MM
LINE_COLOR = (0.7, 0.7, 0.7)

FONT_PATH = r"C:\Windows\Fonts\msgothic.ttc"
FONT_NAME = "msgothic"

OPTIONS = [
    "タスク",
    "アイデア",
    "思考・考察",
    "コミュニケーション",
    "学習・情報収集",
    "日常・その他",
]


def draw_guides(page):
    page.draw_line(
        fitz.Point(LINE_MARGIN_X, HEADER_LINE_Y),
        fitz.Point(PAGE_WIDTH - LINE_MARGIN_X, HEADER_LINE_Y),
        color=LINE_COLOR,
        width=0.5,
    )
    page.draw_line(
        fitz.Point(LINE_MARGIN_X, FOOTER_LINE_Y),
        fitz.Point(PAGE_WIDTH - LINE_MARGIN_X, FOOTER_LINE_Y),
        color=LINE_COLOR,
        width=0.5,
    )


def generate_form_a5():
    filename = "Synapsen_BlankSheet_A5_Form.pdf"
    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)

    doc.set_metadata(
        {
            "keywords": "Synapsen:SkipNormalization",
            "producer": f"Generated by Python {sys.version.split()[0]} with PyMuPDF",
            "title": "Synapsen A5 Form Template",
        }
    )

    draw_guides(page)

    try:
        page.insert_font(fontfile=FONT_PATH, fontname=FONT_NAME)
    except Exception:
        pass

    # フォーム配置
    # スケーリング
    scale_factor = 72 / 200
    form_width = 375 * scale_factor
    form_height = 60 * scale_factor

    CM = 72 / 2.54
    x0 = 0.8 * CM
    y0 = 2.0 * CM * 0.3
    x1 = x0 + form_width
    y1 = y0 + form_height

    widget = fitz.Widget()
    widget.rect = fitz.Rect(x0, y0, x1, y1)
    widget.field_type = fitz.PDF_WIDGET_TYPE_COMBOBOX
    widget.field_flags = fitz.PDF_CH_FIELD_IS_COMBO
    widget.field_name = "category_choice"
    widget.choice_values = OPTIONS
    widget.text_font = FONT_NAME
    widget.text_fontsize = 12
    widget.field_value = ""

    page.add_widget(widget)

    doc.save(filename)
    doc.close()
    print(f"作成完了: {filename}")


def generate_note_a5():
    filename = "Synapsen_BlankSheet_A5.pdf"
    doc = fitz.open()
    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)

    doc.set_metadata(
        {
            "keywords": "DPDocType:notebook; Synapsen:SkipNormalization",
            "producer": f"Generated by Python {sys.version.split()[0]} with PyMuPDF",
            "title": "Synapsen A5 Note Template",
        }
    )

    draw_guides(page)

    doc.save(filename)
    doc.close()
    print(f"作成完了: {filename}")


if __name__ == "__main__":
    generate_form_a5()
    generate_note_a5()
